[package]
name = "profiles"
version = "0.1.2"
edition = "2024"

[dependencies]
log = "0.4.27"
serde = "1.0.219"
serde_json = "1.0.140"
image = "0.25.6"
uuid = { version = "1.17.0", features = ["v4", "js"] }
pelican_ui = "1.1.0"
pelican_ui_std = "0.2.1"

